[versions]
spotless = "8.2.1"
shadow = "9.3.1"
hytale = "+"
luckperms = "5.4"

[libraries]
hytale = { group = "com.hypixel.hytale", name = "Server", version.ref = "hytale" }
luckperms-api = { group = "net.luckperms", name = "api", version.ref = "luckperms" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
